FROM golang:1.24.3

ENV VERSION v1.0.48
ENV GOCACHE /tmp
WORKDIR /go/src/github/pratap-t/movies-parser

RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/$VERSION/nancy-$VERSION-linux-amd64 -O nancy && \
    chmod +x nancy && mv nancy /usr/local/bin/nancy
RUN go install -u golang.org/x/lint/golint

COPY . .

RUN go get -v 