FROM golang:1.20.6

ENV VERSION=v1.0.48
ENV GOCACHE=/tmp
ENV PATH=$PATH:/go/bin
WORKDIR /go/src/github/pratap-t/movies-parser
COPY * .

RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/$VERSION/nancy-$VERSION-linux-amd64 -O /usr/local/bin/nancy && \
    chmod +x /usr/local/bin/nancy

RUN go install golang.org/x/lint/golint@latest
RUN go mod download github.com/PuerkitoBio/goquery 
RUN go mod tidy
RUN chmod 777 /go/src/github/pratap-t/movies-parser/*.lock
COPY . .

RUN go get -v 